//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cursus()
        {
            this.Gebruikers = new HashSet<Gebruiker>();
            this.Hoofdstuks = new HashSet<Hoofdstuk>();
        }
    
        public int id { get; set; }
        public string omschrijving { get; set; }
        public int categorieId { get; set; }
        public double prijs { get; set; }
        public bool metKorting { get; set; }
        public int kortingPercentage { get; set; }
        public int instructeurId { get; set; }
        public int aantalResources { get; set; }
        public bool certificaat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Instructeur Instructeur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gebruiker> Gebruikers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hoofdstuk> Hoofdstuks { get; set; }
    }
}
