//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udemy_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lezing
    {
        public int id { get; set; }
        public string omschrijving { get; set; }
        public int tijdsduurInMinuten { get; set; }
        public int hoofdstukId { get; set; }
    
        public virtual Hoofdstuk Hoofdstuk { get; set; }
    }
}
